### ISSUE TITLE
Test_Ascii is failed

### ISSUE THREAD

**Issue by kkamegawa** [Codeer-Software/LambdicSql.SqlServer#5]
@Ishikawa-Tatsuya さん、このテストがDapperで例外起こすんですが、理由わかります？

https://github.com/Codeer-Software/LambdicSql.SqlServer/compare/kkamegawa/20170401#diff-4df9bd3a0bf122681b21da724a1abaddR174

テスト名:	Test_Ascii
テストの完全名:	Test.TestSymbolFuncsString.Test_Ascii
テスト ソース:	C:\GitHub\LambdicSql.SqlServer\Project\Test40\TestSymbolFuncsString.cs : 行 175
テスト成果:	失敗
テスト継続時間:	0:01:06.0833638

結果  のスタック トレース:	
場所 LambdicSql.feat.Dapper.DapperAdapter.Query[T](IDbConnection cnn, BuildedSql sql, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   場所 LambdicSql.feat.Dapper.DapperAdapter.Query[T](IDbConnection cnn, Sql sql, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   場所 LambdicSql.feat.Dapper.DapperAdapter.Query[T](IDbConnection cnn, Sql`1 sql, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   場所 Test.TestSymbolFuncsString.Test_Ascii() 場所 C:\GitHub\LambdicSql.SqlServer\Project\Test40\TestSymbolFuncsString.cs:行 181
結果  のメッセージ:	
テスト メソッド Test.TestSymbolFuncsString.Test_Ascii が例外をスローしました:
System.InvalidOperationException: A parameterless default constructor or one matching signature (System.Int32 Val) is required for <>f__AnonymousType6`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] materialization

**Comment by Ishikawa-Tatsuya** [comment]
Yes. The result of throwing the query is returned as int. But since the return value of Ascii function defined by Mr. Kamekawa is string, Val type of anonymous class is string. Dapper can not solve this. If the class it receives is not an anonymous type and is defined with a real name, Dapper can solve it.
But, in this case, Ascii wrote that int returns the int in the document, so I think that it is good to define as follows.
Int Ascii (char val);

**Comment by kkamegawa** [comment]
Thank you! fixed commit in https://github.com/Codeer-Software/LambdicSql.SqlServer/commit/19054073e9d94f683114f7867d47ec9583655704
